trigger:
  branches:
    include:
      - release/*
  paths:
    include:
      - src/
      - tests/
      - deployment/
pool:
  name: 'AZURE-DEVOPS-AGENTS-POOL-TEST'

variables:
  - group: 'EW-IPDM-MM-Backend-TEST'
  - name: applicationRootDirectory
    value: $(System.DefaultWorkingDirectory)

extends:
  template: ./templates/stages/build_and_deploy_functionapp_v1.yml
  parameters:
    baseDirectory: '$(applicationRootDirectory)'
    packageName: $(applicationPackageName)
    srcPath: $(applicationRootDirectory)/$(applicationSourcePath)/
    testsPath: $(applicationRootDirectory)/$(applicationTestsPath)/
    pythonVersion: $(pythonVersion)
    appName: $(functionAppName)
    azureSubscription: $(serviceConnectionName)
    environment: $(devopsEnvironment)
